### ISSUE TITLE
Request for more datasets

### ISSUE THREAD

**Issue by fmh1art** [mitdbg/palimpzest#48]
Hi, I am very exciting about the application scenario of Palimpzest and want to do more research on it. However, I have not found an appropriate dataset that support analysis over hundreds or thousands of data instances. Could you please share some urls of these datasets or provide a specific research direction where I may find relevant useful datasets?

**Comment by mdr223** [comment]
Hi @fmh1art, if you execute the `testdata/download_testdata.sh` script (found [here](https://github.com/mitdbg/palimpzest/blob/cost-model-improvement/testdata/download_testdata.sh)) this will download a set of datasets which we used in our CIDR paper. If you then execute the `register-sources.sh` script (found [here](https://github.com/mitdbg/palimpzest/blob/cost-model-improvement/testdata/register-sources.sh)) this will register those datasets with your local instance of PZ.

Once you have done that, the `enron-eval` dataset should have 1000 data instances (each instance is an email), whose labels can be found in `testdata/groundtruth/enron-eval.csv`. A label of `1` indicates that the email references fraudulent activity and a label of `0` indicates that it does not. Please let me know if this dataset is not suitable for your needs, and I'd be happy to suggest other options!

**Comment by fmh1art** [comment]
Thanks for your detailed reply! I am sorry I did not clarify my needs: I have already download all datasets you provided, but for some complex tasks like real-estate-eval, I find the dataset is incomplete (with only 30 data instances). If I want to evaluate on larger dataset with more complicated multimodal data, where can I find these datasets?

> Hi @fmh1art, if you execute the `testdata/download_testdata.sh` script (found [here](https://github.com/mitdbg/palimpzest/blob/cost-model-improvement/testdata/download_testdata.sh)) this will download a set of datasets which we used in our CIDR paper. If you then execute the `register-sources.sh` script (found [here](https://github.com/mitdbg/palimpzest/blob/cost-model-improvement/testdata/register-sources.sh)) this will register those datasets with your local instance of PZ.
> 
> Once you have done that, the `enron-eval` dataset should have 1000 data instances (each instance is an email), whose labels can be found in `testdata/groundtruth/enron-eval.csv`. A label of `1` indicates that the email references fraudulent activity and a label of `0` indicates that it does not. Please let me know if this dataset is not suitable for your needs, and I'd be happy to suggest other options!
