### ISSUE TITLE
TypeError: unhashable type: 'LLMConvertBonded'

### ISSUE THREAD

**Issue by mutong184** [mitdbg/palimpzest#50]
when I run the demo "python simpleDemo.py --task enron --datasetid enron-tiny --engine sentinel" there is a problem:
Traceback (most recent call last):
  File "/data/lijiajun/palimpzest/demos/simpleDemo.py", line 517, in <module>
    records, execution_stats = pz.Execute(
                               ^^^^^^^^^^^
  File "/home/lijiajun/.conda/envs/pz2/lib/python3.12/site-packages/palimpzest/execution/execute.py", line 50, in __new__
    ).execute(dataset=dataset, policy=policy)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijiajun/.conda/envs/pz2/lib/python3.12/site-packages/palimpzest/execution/sentinel_execution.py", line 63, in execute
    sentinel_plans = optimizer.optimize(dataset)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijiajun/.conda/envs/pz2/lib/python3.12/site-packages/palimpzest/optimizer/optimizer.py", line 466, in optimize
    plans = [self.get_sentinel_plan(final_group_id)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijiajun/.conda/envs/pz2/lib/python3.12/site-packages/palimpzest/optimizer/optimizer.py", line 358, in get_sentinel_plan
    phys_op_set = set([expr.operator for expr in phys_exprs])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'LLMConvertBonded'

while  it's ok when I run the command "python simpleDemo.py --task enron --datasetid enron-tiny".

**Comment by mdr223** [comment]
Hi @mutong184, thank you for opening this issue!

There is an issue with sentinel execution at the moment which I will be merging in a fix for likely sometime this weekend. If you re-run the command you shared with `--engine nosentinel` I believe it should execute without an error.

I'll be sure to follow up and close this issue once I merge in the fix to sentinel execution.

**Comment by mdr223** [comment]
Hi @mutong184,

Thanks for your patience, I've merged in a change to main which now includes a new demo which should be able to run sentinel exeuction on a small-scale example using our Enron dataset. You can execute it as follows:
```
python demos/optimizerDemo.py --verbose --workload enron --datasetid enron-eval-tiny --executor sequential-mab --sample-budget 15 --exp-name demo
```
You can also run the simple demo without sentinel execution:
```
python simpleDemo.py --verbose --task enron --datasetid enron-eval-tiny
```
